name: "Deploy to Nuget"

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_PATH: src/Certificates/Certificates.csproj
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}\output
  NUGET_SOURCE_URL: 'https://api.nuget.org/v3/index.json'
  
jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
          
      - name: 'Restore packages'
        run: dotnet restore ${{ env.PROJECT_PATH }}
        
      - name: 'Build project'
        run: dotnet build ${{ env.PROJECT_PATH }} --no-restore --configuration Release
        
      - name: 'Get Version'
        id: version
        uses: battila7/get-version-action@v2
        
      - name: 'Pack project'
        run: dotnet pack ${{ env.PROJECT_PATH }} --no-restore --no-build --configuration Release --include-symbols -p:PackageVersion= 1.0.1 --output ${{ env.PACKAGE_OUTPUT_DIRECTORY }}

      - name: 'Push package'
        run: dotnet nuget push ${{ env.PACKAGE_OUTPUT_DIRECTORY }}\*.nupkg -k ${{ secrets.NUGET_AUTH_TOKEN }} -s ${{ env.NUGET_SOURCE_URL }}
        
